# Generated by Django 5.1.2 on 2025-03-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('unclassified', '未分類'), ('cloud_computing', 'クラウドコンピューティング'), ('on_premise', 'オンプレミス'), ('public_cloud', 'パブリッククラウド'), ('private_cloud', 'プライベートクラウド'), ('hybrid_cloud', 'ハイブリッドクラウド'), ('scalability', 'スケーラビリティ'), ('elasticity', '弾力性'), ('pay_as_you_go', '従量課金制'), ('shared_responsibility', '責任共有モデル'), ('aws_pricing_calculator', 'AWS Pricing Calculator'), ('aws_cost_explorer', 'AWS Cost Explorer'), ('ec2', 'EC2'), ('lambda', 'Lambda'), ('ecs', 'ECS'), ('eks', 'EKS'), ('fargate', 'Fargate'), ('s3', 'S3'), ('ebs', 'EBS'), ('efs', 'EFS'), ('s3_glacier', 'S3 Glacier'), ('storage_gateway', 'Storage Gateway'), ('rds', 'RDS'), ('dynamodb', 'DynamoDB'), ('aurora', 'Aurora'), ('redshift', 'Redshift'), ('elasti_cache', 'Amazon ElastiCache'), ('vpc', 'VPC'), ('cloudfront', 'CloudFront'), ('route_53', 'Route 53'), ('direct_connect', 'Direct Connect'), ('elastic_load_balancer', 'Elastic Load Balancer'), ('iam', 'IAM'), ('kms', 'KMS'), ('aws_shield', 'AWS Shield'), ('aws_waf', 'AWS WAF'), ('aws_organizations', 'AWS Organizations'), ('cloudwatch', 'CloudWatch'), ('cloudtrail', 'CloudTrail'), ('aws_config', 'AWS Config'), ('trusted_advisor', 'AWS Trusted Advisor'), ('auto_scaling', 'Auto Scaling'), ('transit_gateway', 'AWS Transit Gateway'), ('security_hub', 'AWS Security Hub'), ('systems_manager', 'AWS Systems Manager'), ('global_accelerator', 'AWS Global Accelerator'), ('aws_privatelink', 'AWS PrivateLink')], default='unclassified', max_length=30),
        ),
    ]
